"""add_connector_user

Revision ID: 426b64003873
Revises: d19c898e1b0f
Create Date: 2026-02-01 19:35:22.355664

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '426b64003873'
down_revision = 'd19c898e1b0f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
