"""add connectors table

Revision ID: a31b6bb17d43
Revises: eacd88a5c06d
Create Date: 2025-05-31 15:55:54.367553

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a31b6bb17d43'
down_revision = 'eacd88a5c06d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('connectors',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=True),
    sa.Column('connector_type', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('last_message_sent', sa.DateTime(timezone=True), nullable=True),
    sa.Column('last_message_received', sa.DateTime(timezone=True), nullable=True),
    sa.Column('last_successful_message', sa.DateTime(timezone=True), nullable=True),
    sa.Column('config', sa.JSON(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_connectors_connector_type'), 'connectors', ['connector_type'], unique=False)
    op.create_index(op.f('ix_connectors_id'), 'connectors', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_connectors_id'), table_name='connectors')
    op.drop_index(op.f('ix_connectors_connector_type'), table_name='connectors')
    op.drop_table('connectors')
    # ### end Alembic commands ###
